"""Live provider validation without changing the active traveler conversation."""
import json,time,os
from pathlib import Path
import requests

ROOT=Path(__file__).resolve().parents[1]
BASE=os.getenv('APPBOOK_URL','http://127.0.0.1:8031')
report={'status':'running','checks':[]}

def check(name,condition):
    assert condition,name
    report['checks'].append(name)
    print('PASS:',name,flush=True)

def post(path,payload):
    response=requests.post(BASE+path,json=payload,timeout=300)
    if not response.ok:raise RuntimeError(f'{path}: {response.status_code} {response.text[:250]}')
    return response.json()

deadline=time.monotonic()+180
while not requests.get(BASE+'/api/status',timeout=30).json()['ready']:
    if time.monotonic()>deadline:raise RuntimeError('Appbook did not finish warming up')
    time.sleep(1)
initial=requests.get(BASE+'/api/state',timeout=90).json()
check('Existing name has original source attribution',initial['preferences']['name']['value']=='richmond' and initial['preferences']['name']['source_turn_id']=='81702b3a-3565-4dcc-9fe0-8e41d618b7c4')
query='what is the current travel location i am aiming for'
retrieved=post('/api/compare/retrieval',{'query':query})
check('Retrieval uses a genuine HNSW execution plan','HNSW' in retrieved['plan'].upper())
paired=post('/api/compare/reranking',{'query':query})
check('Exact reported query succeeds in both comparison lanes',all('lisbon' in paired[lane]['answer'].lower() for lane in ['with','without']))
report['reranking']={lane:paired[lane] for lane in ['without','with']}
workload=post('/api/workloads',{'mode':'synthetic','scenario':'preferences','turns':2,'focus':'Make two short evolving requests. The first must explicitly change seat from aisle to window for this experiment only. The second must ask which seat preference is currently saved and recall the active destination. No web research is necessary.'})
check('Synthetic user inputs are generated by real Claude with actual usage',len(workload['prompts'])==2 and bool(workload['generation']['calls']) and workload['generation']['estimated_usd']>0)
job=post('/api/tokenomics',{'mode':'synthetic','scenario':'preferences','turns':2,'agents':['custom','memorizz','naive','decisions'],'workload_id':workload['id'],'options':{},'context_limit':24000})
check('All four agents receive the same reviewed sequence',job['prompts']==workload['prompts'] and job['workload']['generation']['charged_once'])
while job['status']=='running':
    time.sleep(2)
    job=requests.get(BASE+'/api/tokenomics/'+job['id'],timeout=90).json()
    print('PROGRESS:',job['status'],len(job['rows']),'/',8,flush=True)
check('Four agents complete the evolving synthetic workload',job['status']=='completed' and len(job['rows'])==8 and all(row['status']=='success' for row in job['rows']))
check('Custom and decision lanes persist the preference correction',all(row['current_profile']['seat']=='window' for row in job['rows'] if row['agent'] in {'custom','decisions'}))
check('Every lane has actual provider usage',all(any(row['agent']==agent and row['provider_calls']>0 for row in job['rows']) for agent in job['agents']))
check('Decision lane includes Jev usage',any(row['agent']=='decisions' and row['decision_calls'] for row in job['rows']))
final=requests.get(BASE+'/api/state',timeout=90).json()
check('Experiment preserves active traveler scope and profile',final['scope']==initial['scope'] and final['preferences']==initial['preferences'])
report.update(status='passed',workload=workload,job_id=job['id'],rows=job['rows'])
(ROOT/'revision_live_validation.json').write_text(json.dumps(report,indent=2))
