"use strict";
const $=(selector,root=document)=>root.querySelector(selector);
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=value=>escapeHTML(JSON.stringify(value,null,2));
let status={},state=null,architecturePlayer=null,lastRun=null,chatMessages=[],selectedTable=null,viewCleanup=null,actionPending=false;
const SECTIONS=[['1','Embeddings'],['2','Retrieval'],['3','Reranking'],['4','Grounded answers'],['5','Agentic retrieval'],['6','Session memory'],['7','Semantic cache'],['8','Conversation memory'],['9','Workflow memory'],['10','Compaction & compression'],['11','Memory-aware agent'],['12','Prompt caching']];
async function api(path,payload){const response=await fetch(path,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(typeof result.detail==='string'?result.detail:JSON.stringify(result.detail));return result;}
function toast(message){const el=$('#toast');el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,6000);}
function details(value,title='Inspect observed data'){return `<details class="json-details"><summary>${escapeHTML(title)}</summary><pre>${json(value)}</pre></details>`;}
function richText(text){
 const lines=escapeHTML(text).split('\n');let list=null,grid=null,out='';
 function inline(raw){
  return raw.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>')
   .replace(/(^|[\s(])\*([^*\n]+)\*(?=[\s.,;:!?)]|$)/g,'$1<em>$2</em>')
   .replace(/`([^`]+)`/g,'<code>$1</code>')
   .replace(/\[([^\]]+)\]\(([^\s)]+)\)/g,(match,label,rawURL)=>{
    try{const url=new URL(rawURL.replaceAll('&amp;','&'));return ['http:','https:'].includes(url.protocol)?`<a href="${escapeHTML(url.href)}" target="_blank" rel="noopener noreferrer">${label}</a>`:label;}catch(_){return label;}
   });
 }
 function close(){
  if(list){out+=`</${list}>`;list=null;}
  if(grid){const [head,...body]=grid;out+=`<div class="record-table"><table><thead><tr>${head.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${body.map(row=>`<tr>${row.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;grid=null;}
 }
 for(const raw of lines){
  if(/^\s*\|.*\|\s*$/.test(raw)){if(list)close();const cells=raw.trim().slice(1,-1).split('|').map(c=>c.trim());if(cells.every(c=>/^:?-{2,}:?$/.test(c)))continue;(grid=grid||[]).push(cells.map(inline));continue;}
  if(grid)close();
  const heading=raw.match(/^\s*(#{1,6})\s+(.*)$/);
  if(heading){close();const tag=heading[1].length<=2?'h2':'h3';out+=`<${tag}>${inline(heading[2])}</${tag}>`;}
  else if(/^\s*[-*]\s+/.test(raw)){if(list!=='ul'){close();out+='<ul>';list='ul';}out+=`<li>${inline(raw.replace(/^\s*[-*]\s+/,''))}</li>`;}
  else if(/^\s*\d+[.)]\s+/.test(raw)){if(list!=='ol'){close();out+='<ol>';list='ol';}out+=`<li>${inline(raw.replace(/^\s*\d+[.)]\s+/,''))}</li>`;}
  else if(!raw.trim())close();
  else if(/^\s*(?:---+|\*\*\*+)\s*$/.test(raw)){close();out+='<hr>';}
  else {close();out+=`<p>${inline(raw)}</p>`;}
 }
 close();return out;
}
function table(records,columns){if(!records?.length)return '<p class="hint">No observations yet.</p>';columns=columns||Object.keys(records[0]);return `<div class="record-table"><table><thead><tr>${columns.map(k=>`<th>${escapeHTML(k.replaceAll('_',' '))}</th>`).join('')}</tr></thead><tbody>${records.map(r=>`<tr>${columns.map(k=>`<td>${escapeHTML(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function usageTable(calls=[]){return table(calls.map(c=>({...c,seconds:Number(c.seconds).toFixed(2),estimated_usd:c.estimated_usd===null?'Unknown':Number(c.estimated_usd).toFixed(6)})),['purpose','seconds','input_tokens','cache_write_tokens','cache_read_tokens','output_tokens','estimated_usd']);}
async function busy(button,work){if(!status.ready){toast(status.error||'The models and Oracle are warming up.');return;}if(actionPending)return;actionPending=true;const original=button.textContent,isSelect=button.tagName==='SELECT';button.disabled=true;if(!isSelect)button.textContent='Working…';try{await work();if(!$('#explorer-body').hidden)await loadTables();}catch(error){toast(error.message);}finally{actionPending=false;if(button.isConnected){button.disabled=button.dataset.persistentDisabled==='true';if(!isSelect)button.textContent=original;}}}
function nav(){$('#chapters').innerHTML='<a class="nav" href="#architecture"><span class="nav-number">⌘</span>Reference architecture</a><a class="nav" href="#context"><span class="nav-number">◫</span>Context window</a><a class="nav" href="#tokenomics"><span class="nav-number">↔</span>Tokenomics</a>'+SECTIONS.map(([id,title])=>`<a class="nav" href="#lab/${id}"><span class="nav-number">${id.padStart(2,'0')}</span>${title}</a>`).join('');document.querySelectorAll('.nav').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===(location.hash||'#assistant')));}
async function refreshState(){if(status.ready){state=await api('/api/state');chatMessages=(state.conversation||[]).map(event=>event.payload);}}
function sourceLinks(urls=[]){return urls.filter(url=>{try{return['https:','http:'].includes(new URL(url).protocol);}catch(_){return false;}}).map(url=>`<p><a href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">${escapeHTML(url)}</a></p>`).join('');}
function preferenceCards(preferences=Object.fromEntries(Object.entries(state?.preferences||{}).filter(([k])=>k!=='name'))){const names={seat:'Seat',quiet_room:'Quiet room',refundable_hotel:'Refundable hotel',direct_only:'Nonstop flights',checked_bags:'Checked bags'};return Object.keys(preferences).length?`<div class="preference-cards">${Object.entries(preferences).map(([key,fact])=>`<div class="preference-card" title="Source turn: ${escapeHTML(fact.source_turn_id)}"><span>${names[key]||escapeHTML(key)}</span><b>${typeof fact.value==='boolean'?(fact.value?'Yes':'No'):escapeHTML(fact.value)}</b><small>Remembered from your conversation</small></div>`).join('')}</div>`:'<p class="hint">Ask the assistant to remember a preference.</p>';}
function profileCards(){const fact=state?.preferences?.name;return fact?`<div class="preference-cards"><div class="preference-card" title="Source turn: ${escapeHTML(fact.source_turn_id)}"><span>Name</span><b id="profile-name">${escapeHTML(fact.value)}</b><small>Saved in entity memory · carries across conversations</small></div></div>`:'<p class="hint">Tell the assistant your name to remember it.</p>';}
function tripPanel(){const session=state?.session,trip=session?.state.trip;return `<section class="panel"><div class="panel-head"><h2>Your active trip</h2><span class="pill good">Oracle memory</span></div><div class="panel-body">${trip?`<h3>${escapeHTML(trip.origin||'Origin needed')} → ${escapeHTML(trip.destination||'Destination needed')}</h3><p>${escapeHTML(trip.departure_date||'Date needed')} → ${escapeHTML(trip.return_date||'Date needed')}</p><p>Budget: ${escapeHTML(trip.budget??'Not supplied')} ${escapeHTML(trip.currency||'')}</p><div class="pref-list">${(trip.constraints||[]).map(x=>`<span class="pill">${escapeHTML(x)}</span>`).join('')}</div>`:'<p class="hint">Enter your dates, destination and budget.</p>'}<span class="eyebrow">PROFILE</span>${profileCards()}<span class="eyebrow">REMEMBERED PREFERENCES</span>${preferenceCards()}<label for="trip-request">Save or update this trip</label><textarea id="trip-request" placeholder="Your origin, destination, dates, budget and constraints"></textarea><div class="actions"><button class="button secondary small" id="save-trip">Save trip</button></div></div><div class="status-line"><span>Session v${session?.version||'—'}</span><span>${escapeHTML(state?.backend||status.memory_backend)}</span></div></section>`;}
function bindTrip(){$('#save-trip').onclick=()=>busy($('#save-trip'),async()=>{const request=$('#trip-request').value.trim();if(!request)throw new Error('Enter your trip constraints.');state=await api('/api/trip',{request});route();});}
function traceHTML(run){return run?.inspections?.map((entry,index)=>`<div class="trace-step"><b>Step ${index+1} · ${escapeHTML(entry.action.action.replaceAll('_',' '))}</b><p>${escapeHTML(entry.action.query||entry.action.kind||'')}</p><span class="pill">${entry.budget.after_tokens} context tokens</span><span class="pill good">${entry.usage?.cache_read_tokens??0} cached tokens</span></div>`).join('')||'<p class="hint">Send a request to see decisions and tool outcomes.</p>';}
function travelerControls(){return `<div class="traveler-controls"><div><label for="traveler-profile">Traveler profile</label><select id="traveler-profile">${(state?.users||[]).map(u=>`<option value="${escapeHTML(u.user_id)}" ${u.user_id===state?.scope?.user?'selected':''}>${escapeHTML(u.display_name)}</option>`).join('')}</select></div><button class="button secondary small" id="new-user">＋ New user</button><p class="hint">Each traveler has their own trip, profile and conversation. Switching back restores their last conversation.</p></div><dialog id="user-dialog"><h2>Start with a new traveler</h2><p>This creates an empty profile. Existing travelers stay saved.</p><label for="new-user-label">Profile label</label><input id="new-user-label" maxlength="120" placeholder="For example, Alex’s travel profile"><p class="hint">This label helps you choose a profile. Tell the assistant any name or preferences you want it to remember.</p><div class="actions"><button class="button" id="create-user">Create user</button><button class="button secondary" id="cancel-user">Cancel</button></div></dialog>`;}
function applyTraveler(next){
 const previous=state?.scope?.user;
 if(previous){const job=localStorage.getItem('tokenomics-job');if(job)localStorage.setItem('tokenomics-job:'+previous,job);}
 if(viewCleanup){viewCleanup();viewCleanup=null;}
 state=next;lastRun=next.last_run;chatMessages=(next.conversation||[]).map(e=>e.payload);
 const job=localStorage.getItem('tokenomics-job:'+next.scope.user);
 if(job)localStorage.setItem('tokenomics-job',job);else localStorage.removeItem('tokenomics-job');
 sessionStorage.removeItem('semantic-comparison-id');selectedTable=null;$('#table-grid').innerHTML='';$('#row-inspector').textContent='';
 renderAssistant();
}
function bindTravelerControls(){
 $('#new-user').onclick=()=>{if(actionPending){toast('Finish the current request before changing traveler.');return;}$('#user-dialog').showModal();$('#new-user-label').focus();};
 $('#cancel-user').onclick=()=>$('#user-dialog').close();
 $('#create-user').onclick=()=>busy($('#create-user'),async()=>{const label=$('#new-user-label').value.trim();if(!label)throw new Error('Enter a profile label.');applyTraveler(await api('/api/users',{display_name:label}));});
 $('#traveler-profile').onchange=e=>{const user_id=e.target.value;if(actionPending){e.target.value=state.scope.user;toast('Finish the current request before changing traveler.');return;}busy(e.target,async()=>applyTraveler(await api('/api/users/select',{user_id})));};
}
function renderAssistant(){$('#stage').innerHTML=`<div class="hero"><span class="eyebrow">PERSONAL TRAVEL · MEMORY IN ACTION</span><h1>A trip worth <em>remembering.</em></h1><p>Research your trip with live search and durable preferences. Open the context window to see which memories reach each decision.</p><div class="hero-badges"><span class="pill good">Oracle AI Database · HNSW</span><span class="pill">Opus 5.5</span><span class="pill">Tavily live search</span></div></div><div class="workspace"><div class="stack"><section class="panel"><div class="panel-head"><h2>Travel assistant</h2><div class="header-actions"><span class="pill good">Live</span><button class="button secondary small" id="new-conversation">＋ New conversation</button></div></div>${travelerControls()}<div class="chat-log" id="chat-log"></div><div class="chat-input"><label for="chat-message">Your request</label><textarea id="chat-message" placeholder="Where would you like to go? What should I remember?"></textarea><div class="actions"><button class="button" id="send">Send request ↗</button><a class="button secondary" href="#context">Inspect context</a></div><p class="hint">Web evidence needs supplier verification. Reservations require a supplier API.</p></div></section><section class="panel"><div class="panel-head"><h2>Decisions and tool outcomes</h2></div><div class="panel-body" id="trace">${traceHTML(lastRun||state?.last_run)}</div></section></div><div class="stack">${tripPanel()}<section class="panel"><div class="panel-head"><h2>Explore your agent</h2></div><div class="panel-body"><div class="actions"><a href="#architecture" class="button secondary">Architecture</a><a href="#tokenomics" class="button secondary">Compare agents</a><a href="#lab/10" class="button secondary">Compare compaction</a></div></div></section></div></div><dialog id="conversation-dialog"><h2>Start a new conversation</h2><p>Your messages start fresh. Remembered preferences carry over.</p><label class="inline-label"><input id="keep-trip" type="checkbox" checked> Keep the active trip</label><div class="actions"><button class="button" id="start-conversation">Start conversation</button><button class="button secondary" id="cancel-conversation">Cancel</button></div></dialog>`;
 renderMessages();bindTrip();bindTravelerControls();$('#new-conversation').onclick=()=>$('#conversation-dialog').showModal();$('#cancel-conversation').onclick=()=>$('#conversation-dialog').close();$('#start-conversation').onclick=()=>busy($('#start-conversation'),async()=>{state=await api('/api/conversations',{keep_trip:$('#keep-trip').checked});chatMessages=[];lastRun=null;renderAssistant();});
 $('#send').onclick=()=>busy($('#send'),async()=>{const message=$('#chat-message').value.trim();if(!message)throw new Error('Enter a request.');chatMessages.push({role:'user',content:message});renderMessages();lastRun=await api('/api/chat',{message});state=lastRun.snapshot;chatMessages.push({role:'assistant',content:lastRun.answer,sources:lastRun.sources});renderAssistant();});}
function renderMessages(){$('#chat-log').innerHTML=chatMessages.length?chatMessages.map(m=>`<article class="message ${m.role}"><div class="message-meta">${m.role==='user'?'TRAVELER':'WAYFINDER'}</div><div class="message-body">${richText(m.content)}${sourceLinks(m.sources)}</div></article>`).join(''):'<div class="empty-chat"><div class="orb">↗</div><h3>A fresh conversation.</h3><p>Tell me your plans, or ask about a remembered preference.</p></div>';}
async function renderContext(){$('#stage').innerHTML='<div class="hero"><span class="eyebrow">CONTEXT WINDOW</span><h1>See what <em>Claude sees.</em></h1><p>Stable instructions come first. Current trip, preferences, conversation and workflow memories follow.</p></div><section class="panel"><div class="panel-head"><h2>Memory at each invocation</h2><button class="button secondary small" id="refresh-context">Refresh</button></div><div class="panel-body" id="context-content">Loading…</div></section>';
 async function load(){const data=await api('/api/context'),iterations=data.last_run?.inspections||[];$('#context-content').innerHTML=`<label for="context-iteration">Invocation</label><select id="context-iteration"><option value="current">Current memory</option>${iterations.map((r,i)=>`<option value="${i}">Step ${i+1} · ${escapeHTML(r.action.action)}</option>`).join('')}</select><div id="context-invocation"></div>`;function inspect(){const selected=$('#context-iteration').value,entry=selected==='current'?{context:data.dynamic_context,budget:data.budget}:iterations[Number(selected)],context=entry.context;$('#context-invocation').innerHTML=`<div class="hero-badges"><span class="pill">${entry.budget.after_tokens} / ${entry.budget.limit_tokens} tokens</span><span class="pill good">${entry.usage?.cache_read_tokens??0} cached tokens</span></div><div class="comparison-grid"><section><h3>Stable prefix</h3><details><summary>Read the instructions Claude receives</summary><div class="prompt-text" id="stable-context">${richText((data.last_run?.prefix||data.prefix).map(b=>b.text).join('\n\n'))}</div></details><h3>Active trip and preferences</h3><div class="memory-facts">${Object.entries(context.current_profile||{}).map(([k,v])=>`<span class="pill">${escapeHTML(k)}: ${escapeHTML(v.value)}</span>`).join('')}</div><p>${escapeHTML(context.session?.state?.trip?.origin||'')} → ${escapeHTML(context.session?.state?.trip?.destination||'')}</p></section><section id="dynamic-context"><h3>Conversation</h3>${(context.recent_conversation||[]).map(t=>`<div class="memory-preview"><b>${escapeHTML(t.payload.role)}</b><p>${escapeHTML(t.payload.content)}</p></div>`).join('')||'<p class="hint">No active conversation turns.</p>'}<h3>Workflow memory</h3>${(context.workflow_memory||[]).map(e=>`<div class="memory-preview"><b>${escapeHTML(e.decision.action)} · ${escapeHTML(e.status)}</b><p>${escapeHTML(e.decision.query||'')}</p></div>`).join('')}<h3>Memory placeholders</h3>${(context.memory_placeholders||[]).map(p=>`<div class="memory-preview"><b>${escapeHTML(p.kind)}</b><p>${escapeHTML(p.description)}</p><small>${escapeHTML(p.memory_id)}</small></div>`).join('')}</section></div>`;}$('#context-iteration').onchange=inspect;inspect();}
 $('#refresh-context').onclick=()=>busy($('#refresh-context'),load);try{await load();}catch(error){toast(error.message);}}
async function loadTables(){try{const tables=await api('/api/tables');$('#table-list').innerHTML=tables.map(t=>`<button class="table-button" data-table="${t.name}">${t.name}<small>${t.count}</small></button>`).join('');$('#table-count').textContent=tables.reduce((n,t)=>n+t.count,0)+' memory records';document.querySelectorAll('[data-table]').forEach(b=>b.onclick=()=>loadTable(b.dataset.table));if(selectedTable)await loadTable(selectedTable);}catch(error){toast(error.message);}}
async function loadTable(name){selectedTable=name;const data=await api('/api/tables/'+name);$('#table-head').textContent=name;$('#table-grid').innerHTML=table(data.rows);$('#table-grid').querySelectorAll('tbody tr').forEach((tr,i)=>tr.onclick=()=>$('#row-inspector').textContent=JSON.stringify(data.rows[i],null,2));}
function route(){if(viewCleanup){viewCleanup();viewCleanup=null;}if(architecturePlayer){architecturePlayer.reset();architecturePlayer=null;}if(location.hash.startsWith('#lesson/')){location.hash='#lab/'+location.hash.slice(8);return;}nav();$('#sidebar').classList.remove('open');if(location.hash==='#architecture')architecturePlayer=renderArchitecture();else if(location.hash==='#context')renderContext();else if(location.hash==='#tokenomics')renderTokenomics();else if(location.hash.startsWith('#lab/'))renderLab(location.hash.slice(5));else renderAssistant();window.scrollTo(0,0);}
async function pollStatus(){try{const previous=status.ready;status=await api('/api/status');$('#db-status').textContent='Oracle · '+(status.ready?'connected':'warming');$('#model-status').textContent=status.responder;if(status.ready&&!previous){await refreshState();route();}if(status.error)toast(status.error);}catch(error){$('#db-status').textContent='Server unavailable';}if(!status.ready)setTimeout(pollStatus,2000);}
async function boot(){await pollStatus();route();window.addEventListener('hashchange',route);$('#theme').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';};$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#explorer-toggle').onclick=async()=>{const body=$('#explorer-body');body.hidden=!body.hidden;$('#explorer-toggle').setAttribute('aria-expanded',String(!body.hidden));if(!body.hidden)await loadTables();};}
boot();
