"use strict";
function heading(number,title,description){return `<div class="hero"><span class="eyebrow">${number?'SECTION '+String(number).padStart(2,'0'):'LIVE EXPERIMENT'}</span><h1>${title}</h1><p>${description}</p></div>`;}
function resultMetrics(m={}){return `<div class="mini-metrics"><span><small>Latency</small><b>${Number(m.seconds||0).toFixed(2)} s</b></span><span><small>API estimate</small><b>${m.estimated_usd===null?'Unknown':'$'+Number(m.estimated_usd||0).toFixed(6)}</b></span><span><small>Model calls</small><b>${m.provider_calls||0}</b></span><span><small>Cached input</small><b>${m.cache_read_tokens||0}</b></span></div>`;}
function passages(items=[]){return items.map((r,i)=>`<article class="source-result"><span class="rank">${i+1}</span><div><b>${escapeHTML(r.metadata?.title||r.metadata?.description||'Stored passage')}</b><p>${escapeHTML(r.text)}</p>${sourceLinks(r.metadata?.url?[r.metadata.url]:[])}<span class="pill">Cosine distance ${Number(r.distance).toFixed(4)}</span>${r.rerank_score!==undefined?`<span class="pill good">Rerank ${Number(r.rerank_score).toFixed(3)}</span>`:''}</div></article>`).join('');}
function renderLab(id){
 if(!SECTIONS.some(s=>s[0]===id)){location.hash='#assistant';return;}
 if(id==='1'){renderEmbeddings();return;}
 if(id==='2'){renderRetrieval();return;}
 if(['3','7','10'].includes(id)){renderComparison(id);return;}
 if(['5','11'].includes(id)){renderAssistant();const title=id==='5'?'Agentic retrieval':'The memory-aware agent';$('.hero').innerHTML=`<span class="eyebrow">SECTION ${id.padStart(2,'0')}</span><h1>${title}</h1><p>Send a request and watch the agent choose searches, recall memories and finish with a grounded answer.</p>`;return;}
 if(id==='6'){$('#stage').innerHTML=heading(id,'A trip that <em>persists.</em>','Update the active trip, then reload it from Oracle.')+`<div class="workspace">${tripPanel()}<section class="panel"><div class="panel-head"><h2>Durable state</h2><button id="reload-session" class="button secondary small">Reload memory</button></div><div class="panel-body"><div class="metric" id="session-version">v${state?.session?.version||'—'}</div><p>Active conversation: <span id="session-thread">${escapeHTML(state?.scope?.thread||'')}</span></p><p class="hint">Conversation history starts fresh when you use New conversation. Preferences persist across threads.</p></div></section></div>`;bindTrip();$('#reload-session').onclick=()=>busy($('#reload-session'),async()=>{await refreshState();renderLab('6');});return;}
 if(id==='8'){renderConversation();return;}
 if(id==='9'){renderWorkflow();return;}
 if(id==='12'){renderPromptCache();return;}
 if(id==='4'){renderRag();return;}
}
async function renderEmbeddings(){
 $('#stage').innerHTML=heading('1','Explore the <em>memory space.</em>','Live stored embeddings, a query you control, and cosine distance computed across every dimension.')+`<div class="embedding-layout"><section class="panel"><div class="panel-head"><h2>Live vector space</h2><span id="vector-count" class="pill">Loading vectors</span></div><canvas id="embedding-space" class="embedding-canvas" aria-label="Interactive projection of actual memory embeddings"></canvas><div class="panel-body"><p class="hint">Drag to rotate · scroll to zoom · select a memory. This is a 3D PCA view of 384-dimensional vectors, not a replacement for their full-space distance.</p><label for="embedding-query">Query the space</label><input id="embedding-query" placeholder="Type a query; distances update as you type"><label for="memory-text">Add your own memory</label><textarea id="memory-text" placeholder="A preference, fact or passage you want to embed"></textarea><button id="add-memory" class="button secondary">Embed and store memory</button></div></section><div class="stack"><section class="panel"><div class="panel-head"><h2>Nearest memories</h2></div><div class="panel-body" id="embedding-neighbors">Loading…</div></section><section class="panel"><div class="panel-head"><h2>Distance, dimension by dimension</h2></div><div class="panel-body"><div id="selected-memory" class="memory-preview">Select a memory.</div><div class="metric" id="cosine-value">—</div><p class="hint" id="distance-value">Send a query to calculate cosine distance.</p><label>Query vector · all 384 dimensions</label><canvas id="query-vector" class="vector-heatmap"></canvas><label>Selected memory · all 384 dimensions</label><canvas id="memory-vector" class="vector-heatmap"></canvas><label for="dimension-step">Accumulated dot product · <span id="dimension-label">384 / 384</span></label><input type="range" id="dimension-step" min="0" max="384" value="384"><div class="actions"><button class="button secondary small" id="animate-distance">Play calculation</button><span class="pill" id="dot-product">dot product —</span></div><p class="hint">The animation adds actual per-dimension products. The final cosine uses both full vector norms.</p></div></section></div></div>`;
 let data=null,selected=null,timer=null,sequence=0,frame=null,closed=false;
 const view=new EmbeddingView($('#embedding-space'),p=>{selected=p;showDistance();});
 function showDistance(){if(!selected||!$('#selected-memory'))return;$('#selected-memory').textContent=selected.text;vectorHeatmap($('#memory-vector'),selected.vector);if(!data?.query)return;const q=data.query.vector,v=selected.vector,n=Number($('#dimension-step').value),dot=q.reduce((sum,x,i)=>sum+(i<n?x*v[i]:0),0),normQ=Math.sqrt(q.reduce((s,x)=>s+x*x,0)),normV=Math.sqrt(v.reduce((s,x)=>s+x*x,0)),cosine=q.reduce((s,x,i)=>s+x*v[i],0)/(normQ*normV);$('#cosine-value').textContent=cosine.toFixed(4);$('#distance-value').textContent=`Cosine distance: ${(1-cosine).toFixed(4)} · query norm ${normQ.toFixed(4)} · memory norm ${normV.toFixed(4)}`;$('#dimension-label').textContent=`${n} / ${q.length}`;$('#dot-product').textContent=`Σ qᵢvᵢ = ${dot.toFixed(5)}`;vectorHeatmap($('#query-vector'),q);}
 async function update(memory_text=''){const ticket=++sequence;const result=await api('/api/embeddings',{query:$('#embedding-query').value.trim(),memory_text});if(closed||ticket!==sequence)return;data=result;$('#vector-count').textContent=`${result.points.length} memories · ${result.dimensions}D`;$('#embedding-neighbors').innerHTML=result.points.length?result.points.slice(0,8).map((p,i)=>`<button class="neighbor-button" data-id="${escapeHTML(p.id)}"><span>${i+1}</span><b>${escapeHTML(p.text.slice(0,100))}</b><small>${p.cosine_distance!==undefined?p.cosine_distance.toFixed(4):'Stored vector'}</small></button>`).join(''):'<p class="hint">Add a memory here or ingest search evidence in Retrieval.</p>';view.update(result);document.querySelectorAll('.neighbor-button').forEach(b=>b.onclick=()=>{selected=data.points.find(p=>p.id===b.dataset.id);view.selected=selected.id;view.draw();showDistance();});}
 $('#embedding-query').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>update().catch(e=>toast(e.message)),550);};$('#add-memory').onclick=()=>busy($('#add-memory'),async()=>{const text=$('#memory-text').value.trim();if(!text)throw new Error('Enter a memory to embed.');await update(text);$('#memory-text').value='';});$('#dimension-step').oninput=showDistance;
 $('#animate-distance').onclick=()=>{if(!data?.query){toast('Type a query first.');return;}cancelAnimationFrame(frame);let start=null;function step(t){if(closed)return;start=start??t;$('#dimension-step').value=Math.min(384,Math.floor((t-start)/6));showDistance();if(Number($('#dimension-step').value)<384)frame=requestAnimationFrame(step);}frame=requestAnimationFrame(step);};
 viewCleanup=()=>{closed=true;clearTimeout(timer);cancelAnimationFrame(frame);view.destroy();};try{await update();}catch(e){toast(e.message);}
}
function renderRetrieval(){
 $('#stage').innerHTML=heading('2','Find the <em>right memories.</em>','Send a query into the live Oracle HNSW index and inspect the returned passages.')+`<section class="panel"><div class="panel-body"><label for="retrieval-query">Your query</label><textarea id="retrieval-query" placeholder="Search stored evidence, or collect current supplier policies"></textarea><label class="inline-label"><input id="fetch-web" type="checkbox"> Search Tavily and store fresh evidence first</label><button class="button" id="retrieve">Retrieve memories</button></div></section><div class="metrics-strip" id="retrieval-metrics"></div><div class="source-grid" id="retrieved-passages"></div>`;
 $('#retrieve').onclick=()=>busy($('#retrieve'),async()=>{const query=$('#retrieval-query').value.trim();if(!query)throw new Error('Enter a query.');const result=await api('/api/compare/retrieval',{query,fetch_web:$('#fetch-web').checked});$('#retrieval-metrics').innerHTML=`<span class="pill good">${result.candidates.length} passages</span><span class="pill">${result.seconds.toFixed(3)} s retrieval</span><span class="pill good">${result.index_used} index</span>`;$('#retrieved-passages').innerHTML=passages(result.candidates)||'<p>No passages found. Collect fresh evidence and try again.</p>';});
}
function renderComparison(id){
 const config={'3':{title:'Give relevance a <em>second look.</em>',description:'One query, the same candidate pool, one passage per answer. Compare vector rank with reranked context.',left:'Vector search · top 1',right:'Reranked · top 1',technique:'reranking',placeholder:'Ask a question about your stored travel evidence'},'7':{title:'Ask again. <em>Reuse wisely.</em>',description:'Compare a fresh Claude response with semantic answer reuse. Repeat or paraphrase a stable agent-memory question.',left:'Cache disabled',right:'Semantic cache',technique:'semantic-cache',placeholder:'Ask an educational question about agent memory'},'10':{title:'Less context. <em>Originals preserved.</em>',description:'Compare answers from full active history and an LLM summary. Also measure lossless archive compression.',left:'Full conversation',right:'Compacted conversation',technique:'compaction',placeholder:'Ask a question about the conversation you have had'}}[id];
 let cacheId=sessionStorage.getItem('semantic-comparison-id')||crypto.randomUUID().replaceAll('-','');sessionStorage.setItem('semantic-comparison-id',cacheId);
 $('#stage').innerHTML=heading(id,config.title,config.description)+`<section class="panel"><div class="panel-body"><label for="shared-query">One query for both agents</label><textarea id="shared-query" placeholder="${config.placeholder}"></textarea>${id==='3'?'<label class="inline-label"><input id="fetch-web" type="checkbox"> Search Tavily and store fresh evidence first</label>':''}<div class="actions"><button class="button" id="compare">Send to both ↗</button>${id==='10'?'<button class="button secondary" id="auto-compact">Auto compact conversation</button>':''}${id==='7'?'<button class="button secondary" id="reset-semantic">Start with an empty cache</button>':''}</div></div></section><div id="comparison-note" class="metrics-strip"></div><div class="comparison-grid"><section class="panel"><div class="panel-head"><h2>${config.left}</h2><span class="pill">A</span></div><div class="comparison-chat" id="chat-without"><p class="hint">Your query will appear here.</p></div><div class="panel-body" id="metrics-without"></div><div id="context-without" class="panel-body"></div></section><section class="panel"><div class="panel-head"><h2>${config.right}</h2><span class="pill good">B</span></div><div class="comparison-chat" id="chat-with"><p class="hint">Your query will appear here.</p></div><div class="panel-body" id="metrics-with"></div><div id="context-with" class="panel-body"></div></section></div><div id="comparison-extra"></div>`;
 let closed=false;viewCleanup=()=>{closed=true;};
 if(id==='10')$('#auto-compact').onclick=()=>busy($('#auto-compact'),async()=>{
  const result=await api('/api/compaction',{});if(closed)return;await refreshState();if(closed)return;
  $('#comparison-note').innerHTML=`<span class="pill">${result.before_tokens} → ${result.after_tokens} context tokens</span><span class="pill good">${result.compacted} messages compacted</span><span class="pill">${result.before_active_turns} → ${result.after_active_turns} active messages</span>`;
  $('#comparison-extra').innerHTML=`<section class="panel"><div class="panel-head"><h2>Compaction applied</h2><span class="pill ${result.originals_preserved?'good':'warn'}">${result.originals_preserved?'Originals preserved':'Check source retention'}</span></div><div class="panel-body">${result.summary?richText(result.summary.summary):`<p>${escapeHTML(result.description)}</p>`}${result.memory_id?`<p class="hint">Summary reference: ${escapeHTML(result.memory_id)}</p><p>${escapeHTML(result.description)}</p><button id="expand-compaction" class="button secondary small">Read linked originals</button><div id="compaction-originals"></div>`:''}${resultMetrics(result.metrics)}<p class="hint">${result.after_tokens<result.before_tokens?'The selected context is smaller.':'This short conversation did not shrink; summary metadata can cost more tokens than a small source.'}</p></div></section>`;
  if(result.memory_id)$('#expand-compaction').onclick=()=>busy($('#expand-compaction'),async()=>{const page=await api('/api/labs/10',{memory_id:result.memory_id,offset:0});if(!closed)$('#compaction-originals').innerHTML=`<div class="prompt-text">${richText(page.content||page.preview||JSON.stringify(page,null,2))}</div>`;});
 });
 if(id==='7')$('#reset-semantic').onclick=()=>{cacheId=crypto.randomUUID().replaceAll('-','');sessionStorage.setItem('semantic-comparison-id',cacheId);$('#comparison-note').textContent='New cache namespace selected. The next eligible request is cold.';};
 $('#compare').onclick=()=>busy($('#compare'),async()=>{const query=$('#shared-query').value.trim();if(!query)throw new Error('Enter one query for both sides.');const result=await api('/api/compare/'+config.technique,{query,cache_id:cacheId,fetch_web:$('#fetch-web')?.checked||false});if(closed)return;for(const lane of ['without','with']){const item=result[lane];$('#chat-'+lane).innerHTML=`<article class="message user"><div class="message-meta">YOU</div><div class="message-body">${richText(query)}</div></article><article class="message"><div class="message-meta">${lane==='with'?config.right:config.left}</div><div class="message-body">${richText(item.answer)}</div></article>`;$('#metrics-'+lane).innerHTML=resultMetrics(item.metrics);}
 if(id==='3'){$('#comparison-note').innerHTML=result.same_passage?'<span class="pill">Both selected the same passage on this query</span>':'<span class="pill good">Reranking selected a different passage</span>';$('#context-without').innerHTML='<h3>Context used</h3>'+passages([result.without.context]);$('#context-with').innerHTML='<h3>Context used</h3>'+passages([result.with.context]);$('#comparison-extra').innerHTML=`<div class="comparison-grid"><section class="panel"><div class="panel-head"><h2>Vector order</h2></div><div class="panel-body">${passages(result.candidates)}</div></section><section class="panel"><div class="panel-head"><h2>After reranking</h2></div><div class="panel-body">${passages(result.reranked)}</div></section></div>`;}
 if(id==='7'){$('#comparison-note').innerHTML=`<span class="pill ${result.with.cache_hit?'good':'warn'}">${result.with.cache_hit?'Semantic cache hit · no Claude call':'Semantic cache miss · answer stored'}</span><span class="pill">${result.without.metrics.provider_calls} direct model call · ${result.with.metrics.provider_calls} cached-side model calls</span>`;}
 if(id==='10'){$('#comparison-note').innerHTML=`<span class="pill">${result.without.context_tokens} → ${result.with.context_tokens} input tokens</span><span class="pill good">${Math.abs(result.tokens_saved)} ${result.tokens_saved>=0?'fewer':'more'} input tokens</span><span class="pill">Active history preserved</span>`;$('#context-without').innerHTML='<h3>Full source conversation</h3>'+result.turns.map(t=>`<div class="memory-preview"><b>${escapeHTML(t.role)}</b><p>${escapeHTML(t.content)}</p></div>`).join('');$('#context-with').innerHTML='<h3>Summary used</h3><div class="memory-preview">'+richText(result.summary.summary)+'</div>';const a=result.archive;$('#comparison-extra').innerHTML=`<section class="panel"><div class="panel-head"><h2>Lossless storage compression</h2><span class="pill good">Exact reconstruction verified</span></div><div class="panel-body"><div class="mini-metrics"><span><small>Original source</small><b>${a.original_bytes.toLocaleString()} bytes</b></span><span><small>Compressed archive</small><b>${a.compressed_bytes.toLocaleString()} bytes</b></span><span><small>Storage saved</small><b>${(100*a.bytes_saved/a.original_bytes).toFixed(1)}%</b></span></div><p class="hint">Lossless compression saves storage. The LLM summary changes context size and can omit detail. Generating this summary cost ${result.summary_metrics.estimated_usd===null?'Unknown':'$'+Number(result.summary_metrics.estimated_usd).toFixed(6)} and ${result.summary_metrics.seconds.toFixed(2)} s.</p></div></section>`;}
 });
}
function renderConversation(){$('#stage').innerHTML=heading('8','Remember what <em>matters.</em>','State a preference, then see its current value alongside the source conversation.')+`<div class="workspace"><section class="panel"><div class="panel-head"><h2>Conversation</h2></div><div class="panel-body">${(state?.conversation||[]).map(t=>`<article class="message ${t.payload.role}"><div class="message-meta">${escapeHTML(t.payload.role)}</div><div class="message-body">${richText(t.payload.content)}</div></article>`).join('')||'<p class="hint">Start a conversation with the travel assistant.</p>'}</div></section><section class="panel"><div class="panel-head"><h2>Current remembered preferences</h2></div><div class="panel-body">${preferenceCards()}<label for="preference-input">A preference to remember or correct</label><textarea id="preference-input" placeholder="Remember that I prefer…"></textarea><button class="button" id="remember-preference">Extract and remember</button></div></section></div>`;$('#remember-preference').onclick=()=>busy($('#remember-preference'),async()=>{const query=$('#preference-input').value.trim();if(!query)throw new Error('Enter a preference.');await api('/api/labs/8',{query});await refreshState();renderConversation();});}
function renderWorkflow(){$('#stage').innerHTML=heading('9','Follow each <em>decision.</em>','Actual tool calls, outcomes and failures stored during your agent runs.')+`<section class="panel"><div class="panel-head"><h2>Workflow memory</h2><button class="button secondary small" id="refresh-workflow">Refresh</button></div><div class="panel-body" id="workflow-list"></div></section>`;function show(){const events=state?.workflow||[];$('#workflow-list').innerHTML=events.length?events.map((e,i)=>{const action=e.payload.decision,outcome=e.payload.outcome;return `<div class="workflow-row"><span class="step-orb">${i+1}</span><div><b>${escapeHTML(action.action.replaceAll('_',' '))}</b><span class="pill ${e.status==='success'?'good':'warn'}">${escapeHTML(e.status)}</span><p>${escapeHTML(action.query||action.answer||'')}</p>${outcome.results?sourceLinks(outcome.results.map(r=>r.url)):outcome.message?`<p class="error">${escapeHTML(outcome.message)}</p>`:''}<small>${escapeHTML(e.created_at)}</small></div></div>`;}).join(''):'<p class="hint">Send a travel request to record actual execution steps.</p>';}show();$('#refresh-workflow').onclick=()=>busy($('#refresh-workflow'),async()=>{await refreshState();show();});}
function renderRag(){$('#stage').innerHTML=heading('4','Answer from <em>selected evidence.</em>','Ask a question with your active trip and retrieved sources available to Claude.')+`<section class="panel"><div class="panel-body"><label for="rag-query">Your question</label><textarea id="rag-query" placeholder="What do the stored supplier policies say about this trip?"></textarea><label class="inline-label"><input type="checkbox" id="rag-search"> Collect fresh Tavily evidence first</label><button class="button" id="rag-answer">Get a grounded answer</button></div></section><div id="rag-result"></div>`;$('#rag-answer').onclick=()=>busy($('#rag-answer'),async()=>{const query=$('#rag-query').value.trim();if(!query)throw new Error('Enter a question.');if($('#rag-search').checked)await api('/api/compare/retrieval',{query,fetch_web:true});const result=await api('/api/labs/4',{query});$('#rag-result').innerHTML=`<section class="panel"><div class="panel-body"><div class="message-body">${richText(result.answer)}</div><h3>Evidence selected</h3>${passages(result.passages||[])}</div></section>`;});}
async function renderPromptCache(){$('#stage').innerHTML=heading('12','Reuse the <em>stable prefix.</em>','Watch cache writes and reads reported by Anthropic while your memory context changes.')+`<section class="panel"><div class="panel-head"><h2>Actual agent calls</h2><button class="button secondary small" id="refresh-cache">Refresh usage</button></div><div class="panel-body" id="prompt-cache-results">Loading…</div></section>`;async function load(){const result=await api('/api/labs/12',{}),calls=result.usage.filter(c=>c.purpose==='agent decision');$('#prompt-cache-results').innerHTML=calls.length?`<div class="mini-metrics"><span><small>Prefix tokens reused</small><b>${calls.reduce((n,c)=>n+c.cache_read_tokens,0).toLocaleString()}</b></span><span><small>Prefix tokens written</small><b>${calls.reduce((n,c)=>n+c.cache_write_tokens,0).toLocaleString()}</b></span><span><small>Decisions</small><b>${calls.length}</b></span></div>${calls.map((c,i)=>{const total=c.input_tokens+c.cache_read_tokens+c.cache_write_tokens;return `<div class="cache-bar-row"><b>Call ${i+1}</b><div class="token-bar"><span class="tokens-cached" style="width:${100*c.cache_read_tokens/total}%" title="${c.cache_read_tokens} cache reads"></span><span class="tokens-written" style="width:${100*c.cache_write_tokens/total}%" title="${c.cache_write_tokens} cache writes"></span><span class="tokens-new" style="width:${100*c.input_tokens/total}%" title="${c.input_tokens} uncached inputs"></span></div><small>${total} input tokens</small></div>`;}).join('')}<div class="legend"><span>● Cached prefix</span><span>● New cache write</span><span>● Changing uncached input</span></div>${usageTable(calls)}<p class="hint">Repeated reads count each reuse of the same prefix. Estimated USD includes input, cache and output charges.</p>`:'<p class="hint">Run the travel assistant to collect live prompt-cache counters.</p><a class="button" href="#assistant">Open travel assistant</a>';}$('#refresh-cache').onclick=()=>busy($('#refresh-cache'),load);try{await load();}catch(e){toast(e.message);}}
